GenieBank/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GenieBank.Models;
using Microsoft.AspNet.Identity;

namespace GenieBank.Controllers
{
    public class BankAccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BankAccounts
        public ActionResult Index()
        {
            var accounts = db.BankAccounts.Where(bankAccount => User.Identity.Name == bankAccount.OwnerEmail || User.Identity.Name == bankAccount.RecipientEmail).ToList();
            int accountCount = accounts.Count;
            BankAccount onlyAccount = accounts.FirstOrDefault(); 
            if(accountCount == 1 && User.Identity.Name == onlyAccount.RecipientEmail)
            {
                return RedirectToAction("Details", new { Id = onlyAccount.Id });
            }
            return View(accounts);
        }

        // GET: BankAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(bankAccount);
        }

        // GET: BankAccounts/Create
        public ActionResult Create()
        {
            return View();
        }


		// POST: BankAccounts/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OwnerEmail,OpenDate,RecipientEmail,Name,InterestRate")] BankAccount bankAccount)
        {
            bankAccount.OpenDate = DateTime.Now;
	        if (ModelState.IsValid)
	        {
		        int childEmailInstances = db.BankAccounts.Count(e => e.OwnerEmail == bankAccount.RecipientEmail 
						|| bankAccount.OwnerEmail == bankAccount.RecipientEmail 
						|| e.RecipientEmail == bankAccount.RecipientEmail);
		        if (childEmailInstances > 0)
		        {
			        ModelState.AddModelError("RecipientEmail", "A recipient can only have one account and must have a different email address than their parent. This email address is already assigned.");
			        return View(bankAccount);
		        }
	        }

	        if (ModelState.IsValid)
	        {
		        int parentEmailInstances = db.BankAccounts.Count(e => e.RecipientEmail == bankAccount.OwnerEmail || bankAccount.OwnerEmail == bankAccount.RecipientEmail);
		        if (parentEmailInstances > 0)
		        {
			        ModelState.AddModelError("OwnerEmail", "A parent cannot also be a recipient. This email address is used already assigned to a recipient.");
			        return View(bankAccount);
		        }
	        }

			if (ModelState.IsValid)
            {
                bankAccount.OwnerEmail = User.Identity.Name;
                db.BankAccounts.Add(bankAccount);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bankAccount);
        }

        // GET: BankAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OwnerEmail,OpenDate,RecipientEmail,Name,InterestRate")] BankAccount bankAccount)
        {
            if (ModelState.IsValid)
	        {
		        int childEmailInstances = db.BankAccounts.Count(e => e.OwnerEmail == bankAccount.RecipientEmail || bankAccount.OwnerEmail == bankAccount.RecipientEmail);
		        if (childEmailInstances > 0)
		        {
			        ModelState.AddModelError("RecipientEmail", "A recipient can only have one account and must have a different email address than their parent. This email address is already assigned.");
			        return View(bankAccount);
		        }
	        }

	        if (ModelState.IsValid)
	        {
		        int parentEmailInstances = db.BankAccounts.Count(e => e.RecipientEmail == bankAccount.OwnerEmail || bankAccount.OwnerEmail == bankAccount.RecipientEmail);
		        if (parentEmailInstances > 0)
		        {
			        ModelState.AddModelError("OwnerEmail", "A parent cannot also be a recipient. This email address is used already assigned to a recipient.");
			        return View(bankAccount);
		        }
	        }

			if (ModelState.IsValid)
            {
                db.Entry(bankAccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BankAccount bankAccount = db.BankAccounts.Find(id);
	        if (bankAccount.CurrentBalanceWithInterest() > 0)
	        {
		        return Content("Account cannot be deleted with a positive balance.");
	        }
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // need to find if wishes or transactions exist, if they do then remove			



            db.BankAccounts.Remove(bankAccount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GenieBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using GenieBank.Models;

namespace GenieBank.Controllers
{
	public class HomeController : Controller
	{
		private ApplicationDbContext db = new ApplicationDbContext();

		[AllowAnonymous]
		public ActionResult Index()
		{
			return View();
		}

		[AllowAnonymous]
		public ActionResult FinancialResources()
		{
			return View();
		}

		public ActionResult ProjectStatus()
		{
			ViewBag.Message = "Project Status";

			return View();
		}
	}
}

GenieBank/Views/Home/FinancialResources.cshtml
@{
    ViewBag.Title = "Financial Resources";
}
<nav class="breadcrumb">
	<ol class="breadcrumb">
		<li><a href="@Url.Action("Index","Home")">Home</a></li>
		<li class="active">Financial Resources</li>
	</ol>
</nav>

<div class="row">
	<div class="col-md-6">
		<h2>Resources for Parents</h2>
		<p><a class="btn btn-default" Target="_blank" href="http://time.com/money/4616756/make-your-kid-an-investing-genius/">Article: Make Your Kids An Investing Genius &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="https://www.thebalance.com/top-tips-to-teach-your-kids-about-investing-4115938">Article: 10 Tips To Teach Investing To Kids &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="https://www.consumerfinance.gov/consumer-tools/money-as-you-grow/">Article: Money As You Grow &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="http://www.savingforcollege.com/">Article: Saving For College &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="http://www.cefe.illinois.edu/links/#links13">Even More Links For Parents! &raquo;</a></p>
		<img src="~/Content/images/growingmoney.jpg" alt="Growing Money" height="150" />

	</div>
	<div class="col-md-6">
		<h2>Kids and Money</h2>
		<p><a class="btn btn-default" Target="_blank" href="https://monetta.com/educational-games.html">Moneta Games About Savings and Investing &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="https://www.usmint.gov/kids/games/index.html">Hip Pocket Change Games From The US Mint &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="https://www.treasurydirect.gov/kids/games/games.htm">Treasury Direct Games &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="http://www.piggybank.co.uk/">Oink Online: Money Matters For Kids &raquo;</a></p>
		<hr />
		
		<h2> Teens And Money</h2>
		<p><a class="btn btn-default" Target="_blank" href="https://www.smgww.org/">Compete In The Stock Market Game &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="http://www.themint.org/teens/compounding-calculator.html">Compounding Interest Calculator &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="http://socialfunds.com/">Invest For Good: Social Investing &raquo;</a></p>
		<p><a class="btn btn-default" Target="_blank" href="https://www.daveramsey.com/blog/how-teens-can-become-millionaires">Article: How Teens Become Millionaires &raquo;</a>
	</div>
	
</div>
<div>
	<p><a href="@Url.Action("Index", "Home")">Return To Home Page</a></p>
</div>

GenieBank/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<nav class="breadcrumb">
	<ol class="breadcrumb">
		<li class="active">Home</li>
	</ol>
</nav>

<div class="row">
	<div class="col-md-4">
		<h4>Genie is a web based application to record deposts and withdraws into an account. The target audience is parents wanting to teach their kids to save. Children can add a wish list they want to spend their money on.</h4> 
		<a href="@Url.Action("Index","BankAccounts")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-piggy-bank"></span> Go To List of Your Accounts</a>
		<br />
		<img src="~/Content/images/risingstock.jpg" alt="Rising Stock" width="350" height="70" />
		<br />
		<br />
		Check out the games, articles, and financial calculators - we have something for Kids, Teens, and Parents!
		<a href="@Url.Action("FinancialResources","Home")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-book"></span> Games, Articles, and Financial Calculators </a>
	
	</div>
	
	<div class="col-md-4">
		<div class="carousel slide" data-ride="carousel" id="featured">
			<div class="carousel-inner">
				<div class="item active">
					<img src="~/Content/images/genie3.jpg" alt="Genie Wishes" />
				</div>
				<div class="item">
					<img src="~/Content/images/lamp4.jpg" alt="Genie Lamp 4" />
				</div>
				<div class="item">
					<img src="~/Content/images/genie2.jpg" alt="Genie 2" />
				</div>
				<div class="item">
					<img src="~/Content/images/lamp2.jpg" alt="Lamp 2" />
				</div>
				
			</div><!--carousel inner-->
			<a class="left carousel-control"
			   href="#featured" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<a class="right carousel-control"
			   href="#featured" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div><!--carousel -->
	</div>

	<div class="col-md-4">
		<h4>Sounds great. Sign me up!</h4>
		<p>In order to start an account, the parent must register their email address on our website. </p>
		<a href="@Url.Action("Register","Account")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-plus"></span> Create Parent Login</a>
		<br/>
		<p>Once the parent has registered, create a separate savings account for each recipient. </p>
		<a href="@Url.Action("Index","BankAccounts")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-piggy-bank"></span> Set Up Savings Account For A Recipient</a>
		<br/>
		<p>After a savings account has been created, each recipient must register their email address on our website to access their individual features.</p>
		<a href="@Url.Action("Register","Account")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-plus"></span> Create Recipient Login </a>

		<img src="~/Content/images/growingmoney.jpg" alt="Growing Money" width="350" height="175" /> 
		<br />
	</div>
</div>
<br/>
<script scr="js/script.js"></script>

GenieBank/Views/Home/ProjectStatus.cshtml
@{
    ViewBag.Title = "ProjectStatus";
}

<nav class="breadcrumb">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")">Home</a></li>
        <li class="active">Project Status</li>
    </ol>
</nav>


<h2>Weekly Project Status</h2>


<h3> Final Week</h3>
<ul>
    <li>Antiforgery</li>
    <li>Restrictions to controllers based on user logins</li>
    <li>Verify routing and breadcrumbs correct</li>
    <li>Proper routing upon Login</li>
    <li>Hiding views based on user email</li>
	<li>"No transactions" and "No wishes" added</li>
</ul>
<br />


<h3> September 27, 2017</h3>
<ul>
    <li>Deleted Index for transactions</li>
    <li>Fixed interest rate validation</li>
    <li>Cleaned up breadcrumbs and headings</li>
    <li>Made meaningful link information (add wish, add trans)</li>
    <li>Fixed all save functions (so when you delete a wish it goes to BA details</li>
    <li>Fixed all bottom of page links to return to BA details</li>
</ul>
<br />


<h3> September 20, 2017</h3>
<ul>
    <li>Currency Conversions</li>
    <li>CRUD filtering based on account</li>
    <li>Display Graphic If Interest Over $10</li>
    <li>Filtering by wish and amount </li>
    <li>Validation for dates - transaction can't be future date or previous year, bank acccount can't be editable</li>
    <li>Links on bottom of pages to return to account index or account list</li>
    <li>Carousel added for bonus points</li>
    <li>Breadcrumbs started (need to be sure it passes id)</li>
    <li>Progress Bars for principle/interest and for amount still need for wish</li>

</ul>
<br />


<h3> September 13, 2017</h3>
<ul>
    <li>Foreign key relationships</li>
    <li>Validation for interest rate and transaction amount</li>
    <li>Dates added for wishes and transactions (but needs validation requirements on transactions)</li>
    <li>Added transactions and wishes to bank account details</li>
</ul>
<br />
<h3> September 6, 2017</h3>
<ul>
    <li>Created new project for Genie Bank</li>
    <li>Created ApplicationDbContext class</li>
    <li>Setup database and added string to Web.config</li>
    <li>Created basic model classes (limited validation and navigation). Note we called the bank account BankAccount to distinguish it from the account used to login to the application. </li>
    <li>Created Project Status Page</li>
    <li>Initial Scaffolding (for Controllers and Views)</li>
    <li>Created Initial Menu Bar and Home Page Template</li>
    <li>Installed AntiXSS Library</li>
    <li>Installed Finance Package</li>
</ul>

<a href="@Url.Action("Index","Home")">Return To Home Page</a>