GenieBank/Models/Wish.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GenieBank.Models
{
	public class Wish
	{
		public int Id { get; set; }

		[Display(Name = "Recipient")]
		public string Account { get; set; }

		[DataType(DataType.Date)]
		[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
		[Display(Name = "Date Wish Added")]
		public DateTime WishDate { get; set; }

		[Required(ErrorMessage = "Approximate cost of item is required")]
		[DataType(DataType.Currency)]
		public decimal Cost { get; set; }

		[Required(ErrorMessage = "Description of item is required")]
		public string Description { get; set; }

		[Url]
		[Display(Name = "Website Link")]
		public string WebsiteLink { get; set; }

		public bool Purchased { get; set; }

		public int BankAccountId { get; set; }
		public virtual BankAccount BankAccount { get; set; }

		public bool Affordable()
		{
			decimal currentBalanceWithInterest = BankAccount.Principle();
			if (Cost >= currentBalanceWithInterest)
			{
				return true;
			}
			return false;
		}

		public decimal BalanceAfterPurchase()
		{
			decimal balancePostPurchase = BankAccount.CurrentBalanceWithInterest() - Cost;
			return Math.Round(balancePostPurchase,2);
		}

		public decimal WishPercentBalance()
		{
			decimal percentBalance = BankAccount.CurrentBalanceWithInterest()/Cost;
			return percentBalance;
		}

		public decimal WishPercentAmountNeeded()
		{
			decimal percentAmountNeeded = Math.Abs(BalanceAfterPurchase() / Cost);
			return percentAmountNeeded;
		}

	}
}

GenieBank/Controllers/WishesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GenieBank.Models;

namespace GenieBank.Controllers
{
    public class WishesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

		// GET: Wishes
		public ActionResult Index(string searchString, decimal? searchCost, int? bankAccountId)
		{
            var wish = db.Wish.Include(w => w.BankAccount).Where(x => x.BankAccountId == bankAccountId);
            if (!String.IsNullOrEmpty(searchString))
			{
				wish = wish.Where(w => w.Description.ToUpper().Contains(searchString.ToUpper()));
			}
			if (searchCost.HasValue)
			{
				wish = wish.Where(w => w.Cost == searchCost);
			}
            ViewBag.BankAccountId = bankAccountId;
            var results = wish.ToList();
			return View(results);
		}

		// GET: Wishes/Details/5
		public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wish wish = db.Wish.Find(id);
            if (wish == null)
            {
                return HttpNotFound();
            }
            BankAccount bankAccount = db.BankAccounts.Find(wish.BankAccountId);
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(wish);
        }

		// GET: Wishes/Create
		public ActionResult Create(int BankAccountId, string recipient)
		{
            ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "OwnerEmail");
			if (BankAccountId <= 0)
			{
				return View();
			}
			if (string.IsNullOrWhiteSpace(recipient))
			{
				return View();
			}
            BankAccount bankAccount = db.BankAccounts.Find(BankAccountId);
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var wish = new Wish { BankAccountId = BankAccountId, Account = recipient, WishDate = DateTime.Now };
			return View(wish);
		}

        // POST: Wishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Account,Cost,Description,WebsiteLink,Purchased,WishDate,BankAccountId")] Wish wish)
        {
            if (ModelState.IsValid)
            {
                BankAccount bankAccount = db.BankAccounts.Find(wish.BankAccountId);
                if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                db.Wish.Add(wish);
                db.SaveChanges();
                return RedirectToAction("Details", "BankAccounts", new { Id = wish.BankAccountId });
			}

            ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "OwnerEmail", wish.BankAccountId);
            return View(wish);
        }

        // GET: Wishes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wish wish = db.Wish.Find(id);
            if (wish == null)
            {
                return HttpNotFound();
            }
            BankAccount bankAccount = db.BankAccounts.Find(wish.BankAccountId);
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "OwnerEmail", wish.BankAccountId);
            return View(wish);
        }

        // POST: Wishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Account,Cost,Description,WebsiteLink,Purchased,WishDate,BankAccountId")] Wish wish)
        {
            if (ModelState.IsValid)
            {
                BankAccount bankAccount = db.BankAccounts.Find(wish.BankAccountId);
                if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                db.Entry(wish).State = EntityState.Modified;
                db.SaveChanges();
	            return RedirectToAction("Details", "BankAccounts", new { Id = wish.BankAccountId });
			}
            ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "OwnerEmail", wish.BankAccountId);
            return View(wish);
        }

        // GET: Wishes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wish wish = db.Wish.Find(id);
            if (wish == null)
            {
                return HttpNotFound();
            }
            BankAccount bankAccount = db.BankAccounts.Find(wish.BankAccountId);
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(wish);
        }

        // POST: Wishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wish wish = db.Wish.Find(id);
            BankAccount bankAccount = db.BankAccounts.Find(wish.BankAccountId);
            if (User.Identity.Name != bankAccount.OwnerEmail && User.Identity.Name != bankAccount.RecipientEmail)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Wish.Remove(wish);
            db.SaveChanges();
	        return RedirectToAction("Details", "BankAccounts", new { Id = wish.BankAccountId });
		}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GenieBank/Views/Wishes/Create.cshtml
@model GenieBank.Models.Wish

@{
    ViewBag.Title = "Create Wish";
}

<nav class="breadcrumb">
	<ol class="breadcrumb">
		<li><a href="@Url.Action("Index","Home")">Home</a></li>
		<li><a href="@Url.Action("Index", "BankAccounts", new { id = Model.BankAccountId})">Bank Account List</a></li>
		<li><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">Account Details</a></li>
		<li class="active">Create Wish</li>
	</ol>
</nav>

<h2>Add Wish</h2>

@User.Identity.Name
@Model.BankAccount

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountId, "BankAccountId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
	            @Html.DisplayFor(model => model.BankAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Account, "Account", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebsiteLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebsiteLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WebsiteLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.WishDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WishDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Purchased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Purchased)
                    @Html.ValidationMessageFor(model => model.Purchased, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @Html.HiddenFor(model => model.BankAccountId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
	<p><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">Return To Account Details</a></p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GenieBank/Views/Wishes/Delete.cshtml
@model GenieBank.Models.Wish

@{
    ViewBag.Title = "Delete Wish";
}

<nav class="breadcrumb">
	<ol class="breadcrumb">
		<li><a href="@Url.Action("Index","Home")">Home</a></li>
		<li><a href="@Url.Action("Index", "BankAccounts", new { id = Model.BankAccountId})">Bank Account List</a></li>
		<li><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">@Model.BankAccount.Name's Account Details</a></li>
		<li class="active">Delete a Wish</li>
	</ol>
</nav>

<h2>Delete Wish</h2>

<h3>Are you sure you want to delete this wish?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BankAccount.OwnerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccount.OwnerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebsiteLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebsiteLink)
        </dd>

		<dt>
			@Html.DisplayNameFor(model => model.WishDate)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.WishDate)
		</dd>

        <dt>
            @Html.DisplayNameFor(model => model.Purchased)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchased)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>
<div>
	<p><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">Return To Account Details</a></p>
</div>

GenieBank/Views/Wishes/Details.cshtml
@model GenieBank.Models.Wish

@{
    ViewBag.Title = "Wish Details";
}

<nav class="breadcrumb">
	<ol class="breadcrumb">
		<li><a href="@Url.Action("Index","Home")">Home</a></li>
		<li><a href="@Url.Action("Index", "BankAccounts", new { id = Model.BankAccountId})">Bank Account List</a></li>
		<li><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">@Model.BankAccount.Name's Account Details</a></li>
		<li class="active">Wish Details</li>
	</ol>
</nav>

<h2>Wish Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BankAccount.OwnerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccount.OwnerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccount.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebsiteLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebsiteLink)
        </dd>
		<dt>
			@Html.DisplayNameFor(model => model.WishDate)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.WishDate)
		</dd>

        <dt>
            @Html.DisplayNameFor(model => model.Purchased)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchased)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit Wish", "Edit", new { id = Model.Id })
</p>

<div>
	<p><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">Return To Account Details</a></p>
</div>

GenieBank/Views/Wishes/Edit.cshtml
@model GenieBank.Models.Wish

@{
    ViewBag.Title = "Edit Wish";
}
<nav class="breadcrumb">
	<ol class="breadcrumb">
		<li><a href="@Url.Action("Index","Home")">Home</a></li>
		<li><a href="@Url.Action("Index", "BankAccounts", new { id = Model.BankAccountId})">Bank Account List</a></li>
		<li><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">@Model.BankAccount.Name's Bank Account</a></li>
		<li class="active">Edit Wish</li>
	</ol>
</nav>

<h2>Edit Wish</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountId, "BankAccountId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.BankAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.BankAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.BankAccount.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.BankAccount.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
            </div>
        </div>
		
        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebsiteLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebsiteLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WebsiteLink, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			@Html.LabelFor(model => model.WishDate, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.WishDate, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.WishDate, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.Purchased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Purchased)
                    @Html.ValidationMessageFor(model => model.Purchased, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

		<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
	<p><a href="@Url.Action("Details", "BankAccounts", new { id = Model.BankAccountId})">Return To Account Details</a></p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GenieBank/Views/Wishes/Index.cshtml
@model IEnumerable<GenieBank.Models.Wish>

@{
    ViewBag.Title = "Wish List";
}

<nav class="breadcrumb">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")">Home</a></li>
        <li><a href="@Url.Action("Index", "BankAccounts", new { id = ViewBag.BankAccountId})">Bank Account List</a></li>
        <li><a href="@Url.Action("Details", "BankAccounts", new { id = ViewBag.BankAccountId})">Account Details</a></li>
        <li class="active">Wish Details</li>
    </ol>
</nav>
<h2>Wish List</h2>

<p>
	@using (Html.BeginForm("Index", "Wishes", FormMethod.Get))
	{
        
		<p>
        @Html.Hidden("BankAccountId", (int?) ViewBag.BankAccountId)
		Description: @Html.TextBox("searchString")
		Cost: @Html.TextBox("searchCost")
		<input type = "submit" value = "Filter" />
		</p>
	}
</p>

<table class="table">
    <tr>
        <th>Actions
		</th>
		<th>
            @Html.DisplayNameFor(model => model.Account)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            Balance After Purchase
        </th>
		<th>
			@Html.DisplayNameFor(model => model.WishDate)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Purchased)
		</th>

        <th>
            @Html.DisplayNameFor(model => model.WebsiteLink)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
		<td>
			@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
			@Html.ActionLink("Details", "Details", new { id = item.Id }) |
			@Html.ActionLink("Delete", "Delete", new { id = item.Id })
		</td>
        <td>
            @item.BankAccount.Name
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @item.BalanceAfterPurchase()
        </td>
		<td>
			@Html.DisplayFor(modelItem => item.WishDate)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Purchased)
		</td>

        <td>
            @Html.DisplayFor(modelItem => item.WebsiteLink)
        </td>

    </tr>
}

</table>

<div>
	<p><a href="@Url.Action("Details", "BankAccounts", new { id = ViewBag.BankAccountId})">Back To Account Details</a></p>
</div>